#!/bin/bash

# postinst
#
# Copyright (C) 2015 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

case "$1" in
    configure)
        # On jessie, Chromium is started as "chromium-browser" binary.
        which chromium > /dev/null
        if [ "$?" != "0" ]; then
            # Chromium binary is not in the path, create a symlink.
            # If is not yet installed, the symlink will
            # be resolved automatically when it does.
            ln -sf /usr/bin/chromium-browser /usr/bin/chromium
        fi

        ;;
esac

#DEBHELPER#

exit 0
